<a href="https://colab.research.google.com/github/thanhlamnguyen/lam/blob/main/bai_tap_kiem_dinh_z_t.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import random
from scipy import stats
from statsmodels.stats.weightstats import ztest
import warnings
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


XÂY DỰNG CHƯƠNG TRÌNH KIỂM ĐỊNH Z (HOẶC T) CHO CÁC BÀI TẬP SAU

Gợi ý:

- Số liệu được sinh ngẫu nhiên theo phân phối chuẩn
- Sử dụng gói phần mềm statsmodels để tiến hành kiểm định
- Đối với các bài tập kiểm định giả thuyết thì sinh viên cần phát biểu các giả thuyết (bằng tiếng Việt) $H_{0}$ và $H_{a}$ trước khi lập trình kiểm định

Bài 1: You’re a Q/C inspector for Gallo. The sample standard deviation for 2-liter bottles is .05 liters.  A random sample of 100 bottles showed sasmple mean = 1.99 liters.  What is the 90%  confidence interval estimate of the true mean amount in 2-liter bottles? 

In [5]:
mean = 1.99
std = 0.05
N = 100
samples = np.random.normal(1.99, 0.05, 100)
print(samples[:10])
null_mean = 2
alpha = 0.1

ztest_Score, p_value= ztest(samples, value = null_mean, alternative='larger')
if(p_value <  alpha):
  print("Có bằng chứng để bác bỏ giả thuyết H0")
else:
  print("Chưa có bằng chứng để bác bỏ giả thuyết H0")

[1.91388027 2.05414306 2.05646841 1.95709211 1.93728827 2.04985579
 2.03613111 1.92943922 2.07329008 2.05245706]
Chưa có bằng chứng để bác bỏ giả thuyết H0


Bài 2: You’re a time study analyst in manufacturing.  You’ve recorded the following task times (min.): 3.6, 4.2, 4.0, 3.5, 3.8, 3.1. What is the 90% confidence interval estimate of the population mean task time? 

In [6]:
samples = [3.6, 4.2, 4.0, 3.5, 3.8, 3.1]
null_mean = 3.7 # = (3.6 +4.2+ 4.0+ 3.5+ 3.8+ 3.1)/6
alpha = 0.1

ztest_Score, p_value= ztest(samples, value = null_mean, alternative='larger')
if(p_value <  alpha):
  print("Có bằng chứng để bác bỏ giả thuyết H0")
else:
  print("Chưa có bằng chứng để bác bỏ giả thuyết H0")



Chưa có bằng chứng để bác bỏ giả thuyết H0


Bài 3: Does an average box of cereal contain 368 grams of cereal?  A random sample of 25 boxes had $\overline{\rm x}$ = 372.5.  The company has specified $\sigma$ to be 25 grams.  Test at the .05 level of significance.

[344.99885665 391.01743264 396.14944866 310.34188962 372.24995371
 388.42112903 348.6946612  361.67261851 400.36457879 346.09545722]
Chưa có bằng chứng để bác bỏ giả thuyết H0


Bài 4: You’re a Q/C inspector.  You want to find out if a new machine is making electrical cords to customer specification: average breaking strength of 70 lb. with $\sigma$ = 3.5 lb.  You take a sample of 36 cords & compute a sample mean of 69.7 lb.  At the .05 level of significance, is there evidence that the machine is not meeting the average breaking strength?

In [16]:
mean = 69.7
std = 3.5
N = 36
samples = np.random.normal(69.7, 3.5, 36)
print(samples[:10])
null_mean = 70
alpha = 0.05

ztest_Score, p_value= ztest(samples, value = null_mean, alternative='larger')
if(p_value <  alpha):
  print("Có bằng chứng để bác bỏ giả thuyết H0")
else:
  print("Chưa có bằng chứng để bác bỏ giả thuyết H0")


[71.43648026 65.68207657 72.63662115 70.83034946 70.45077379 62.7347964
 70.60601358 65.11798837 69.90152535 74.84661487]
Chưa có bằng chứng để bác bỏ giả thuyết H0


Bài 5: Does an average box of cereal contain more than 368 grams of cereal?  A random sample of 25 boxes showed $\overline{\rm x}$ =  372.5.  The company has specified $\sigma$ to be 25 grams.  Test at the .05 level of significance.

[343.67951336 357.18526252 363.80866815 400.19190149 329.99562608
 339.31581817 404.61586585 382.5411627  370.66592585 372.76304247]
Chưa có bằng chứng để bác bỏ giả thuyết H0


Bài 6: You’re an analyst for Ford.  You want to find out if the average miles per gallon of Escorts is at least 32 mpg. Similar models have a standard deviation of 3.8 mpg. You take a sample of 60 Escorts & compute a sample mean of 30.7 mpg. At the .01 level of significance, is there evidence that the miles per gallon is less than 32?

In [14]:
mean = 30.7
std = 3.8
N = 60
samples = np.random.normal(30.7, 3.8, 60)
print(samples[:10])
null_mean = 32
alpha = 0.01

ztest_Score, p_value= ztest(samples, value = null_mean, alternative='larger')
if(p_value <  alpha):
  print("Có bằng chứng để bác bỏ giả thuyết H0")
else:
  print("Chưa có bằng chứng để bác bỏ giả thuyết H0")



[30.17373059 27.06756126 31.31371609 31.92007898 32.57274001 24.94519249
 32.44165445 25.34785649 26.05753164 30.70889161]
Chưa có bằng chứng để bác bỏ giả thuyết H0
0.9999999828433509


Bài 7: Does an average box of cereal contain 368 grams of cereal?  A random sample of 25 boxes showed $\overline{\rm x}$ = 372.5.  The company has specified $\sigma$ to be 15 grams.  Find the p-Value.

[367.74440944 367.91920388 354.23441341 373.43279336 365.17601422
 356.00901308 356.73083495 392.23195384 359.65851493 374.51443613]


NameError: ignored

Bài 8: Does an average box of cereal contain more than 368 grams of cereal?  A random sample of 25 boxes showed $\overline{\rm x}$ = 372.5.  The company has specified $\sigma$ to be 15 grams.  Find the p-Value.

In [ ]:
#Code here

Bài 9: You’re an analyst for Ford.  You want to find out if the average miles per gallon of Escorts is less than 32 mpg.   Similar models have a standard deviation of 3.8 mpg.  You take a sample of 60 Escorts & compute a sample mean of 30.7 mpg.  What is the value of the observed level of significance (p-Value)?

In [18]:
mean = 30.7
std = 3.8
N = 60
samples = np.random.normal(30.7, 3.8, 60)
print(samples[:10])
null_mean = 32

ztest_Score, p_value= ztest(samples, value = null_mean, alternative='larger')
print(p_value)


[33.53684409 36.41077341 34.46402016 28.60030636 28.40529042 32.15558302
 33.79599274 35.60184643 29.89262089 33.65386935]
0.9103951438547074


Bài 10: Does an average box of cereal contain 368 grams of cereal?  A random sample of 36 boxes had a mean of 372.5 and a standard deviation of 12 grams. Test at the .05 level of significance.

In [19]:
mean = 372.5
std = 12
N = 36
samples = np.random.normal(372.5, 12, 36)
print(samples[:10])
null_mean = 368
alpha = 0.05

ztest_Score, p_value= ztest(samples, value = null_mean, alternative='larger')
if(p_value <  alpha):
  print("Có bằng chứng để bác bỏ giả thuyết H0")
else:
  print("Chưa có bằng chứng để bác bỏ giả thuyết H0")





[363.93902493 391.35679123 350.48741461 388.1803771  377.21482961
 374.79296049 371.47182473 366.42006454 368.16953525 370.01487729]
Có bằng chứng để bác bỏ giả thuyết H0


Bài 11: You work for the FTC.  A manufacturer of detergent claims that the mean weight of detergent is 3.25 lb.  You take a random sample of 64 containers.  You calculate the sample average to be 3.238 lb. with a standard deviation of .117 lb.  At the .01 level of significance, is the manufacturer correct?

In [20]:
mean = 3.238
std = 0.117
N = 64
samples = np.random.normal(3.238, 0.117, 64)
print(samples[:10])
null_mean = 3.25
alpha = 0.01

ztest_Score, p_value= ztest(samples, value = null_mean, alternative='larger')
if(p_value <  alpha):
  print("Có bằng chứng để bác bỏ giả thuyết H0")
else:
  print("Chưa có bằng chứng để bác bỏ giả thuyết H0")


[3.12780824 2.96994041 3.29344393 3.01258323 3.29763601 2.88269883
 3.3075247  3.18043654 3.29169481 3.2341042 ]
Chưa có bằng chứng để bác bỏ giả thuyết H0


Bài 12: Is the average capacity of batteries less than 140 ampere-hours?  A random sample of 20 batteries had a mean of 138.47 and a standard deviation of 2.66.  Assume a normal distribution. Test at the .05 level of significance.

In [ ]:
#Code here

Bài 13: You’re a marketing analyst for Wal-Mart.  Wal-Mart had teddy bears on sale last week.  The weekly sales of bears sold in 10 stores was: 8  11  0   4   7   8   10   5   8   3. At the .05 level of significance, is there evidence that the average bear sales per store is more than 5?

In [ ]:
#Code here